applicationName: '@project.artifactId@'
applicationVersion: '@project.version@'
bootstrapVersion: '@bootstrap.version@'

info:
  app:
    name: '@project.artifactId@'
    description: '@project.description@'
    version: '@project.version@'

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
camel:
  springboot:
    main-run-controller: true

optConfig: production
PORT: 22
vaultPath: /var/run/secrets/nais.io/vault