applicationName: '@project.artifactId@'
applicationVersion: '@project.version@'
bootstrapVersion: '@bootstrap.version@'

info:
  app:
    name: '@project.artifactId@'
    description: '@project.description@'
    version: '@project.version@'

management:
  security:
    enabled: false

camel:
  springboot:
    main-run-controller: true

optConfig: production
PORT: 22